version: "3.9"
services:
  web:
    image: statspage-image
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - data_scraping=true
        - web_server=true
        - tf_support=false
    ports:
      - "8080:8080"