version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - data_scraping=${data_scraping}
        - web_server=${web_server}
    ports:
      - "8080:8080"